pipelines:
  pull-requests:
    feature/*:
      - step:
          name: Build for feature branch pull request
          script:
            - echo "Hello, feature branch PR!"
  default:
    - step:
        name: All other builds
        script:
          - echo "Hello, World!"
